[package]
name = "facebook_api_rs"
version = "0.1.0"
description = "App Description"
categories = ["wasm"]
license = "MIT"
readme = "./README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib","rlib"]

[dev-dependencies]
wasm-bindgen-test = "0.3.18"


[dependencies]
seed = {git  ="https://github.com/seed-rs/seed", branch="master"}
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
async-trait = "0.1.50"
rand = "0.8.4"

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1

[dependencies.web-sys]
version = "0.3.40"
features = [
    "File",
]

[package.metadata.wasm-pack.profile.release]
wasm-opt = ['-Os']





